# redun configuration.

[backend]
db_uri = sqlite:///redun.db

[executors.default]
type = local
mode = process
max_workers = 64

# [executors.batch]
# type = aws_batch
#
# # Required:
# image =
# queue =
# s3_scratch =
#
# # Optional:
# aws_region =
# role =
# debug = False
