# @package _global_
# Cross-source activity: positive pairs must DIFFER on source
# Forces comparison across lab sites

activity_params:
  name: "crosssource"

average_precision:
  params:
    pos_sameby: ["Metadata_JCP2022", "Metadata_reference_index"]
    pos_diffby: ["Metadata_Source"]
    neg_sameby: ["Metadata_Plate"]
    neg_diffby: ["Metadata_negcon"]
    batch_size: 1000

mean_average_precision:
  params:
    sameby: ["Metadata_JCP2022", "Metadata_Source"]
    null_size: 100000
    threshold: 0.1
    seed: 12527
