name: compound_DL_CPCNN_with_source7_active_union
path: "data/raw/profiles/compound_DL_CPCNN_with_source7_active_union.parquet"
description: "Deep Learning (CPCNN) profiles (with source_7) filtered to union of active perturbations (active in either CP or DL)"
